### ISSUE TITLE
Saving sqlite db to S3 storage

### ISSUE THREAD

**Issue by freefos** [FlowFuse/nr-file-nodes#44]
### Description

I'm currently testing the @flowfuse/nr-file-nodes attached to an Azure bucket to have persistent file storage.
Is there a way to also save my sqlite db (node-red-node-sqlite) to the S3 storage?
If not, will there be a Flowfuse version of the sqlite node?

Thanks in advance.

**Comment by hardillb** [comment]
No, because the sqlite node can only access a local file

**Comment by hardillb** [comment]
And no, the underlying sqlite node can't access remote files, you should use a network accessible SQL database

**Comment by freefos** [comment]
Alright, Thanks for the info hardillb!
